version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - sudo yum install -y google-chrome-stable
      - CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
      - CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
      - wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
      - unzip chromedriver_linux64.zip
      - sudo mv chromedriver /usr/local/bin/
      - sudo chmod +x /usr/local/bin/chromedriver

  build:
    commands:
      - echo "Running WebdriverIO Tests..."
      - npx wdio run wdio.conf.js

  post_build:
    commands:
      - echo "Generating Allure Reports..."
      - npm install -g allure-commandline --save-dev
      - allure generate allure-results --clean -o allure-report
      - echo "Uploading Reports and Screenshots..."
      - aws s3 cp allure-report s3://your-s3-bucket-name/ --recursive
      - aws s3 cp screenshots s3://your-s3-bucket-name/screenshots/ --recursive

artifacts:
  files:
    - allure-report/**
    - screenshots/**

